[mako]
path = "/fr/emersion/Mako"
member = ".*"
signal = 9
signal_process = "waybar"

[bluetooth_removed]
path = "/org/freedesktop/systemd1"
member = "UnitRemoved"
data = "sys-subsystem-bluetooth-devices"
signal = 13
signal_process = "waybar"
exec = 'notify-send "Bluetooth Device removed"'


[bluetooth_added]
path = "/org/freedesktop/systemd1"
member = "UnitNew"
data = "sys-subsystem-bluetooth-devices"
signal = 13
signal_process = "waybar"
exec = 'notify-send "Bluetooth Device connected"'